server:
  cgi:
    session:
      key: PHPSESSID
      service: >
        apps\core\classier\service\SessionService
    context: >
      apps\file\classier\context\WebContext
  swoole:
    session:
      key: PHPSESSID
      service: >
        apps\core\classier\service\SessionService
    context: >
      apps\file\classier\context\WebContext
    http:
      ip: 0.0.0.0
      port: 1800
      options:
        ssl_key_file: null
        ssl_cert_file: null

