server:
  cgi:
    session:
      key: PHPSESSID
      service: >
        apps\core\classier\service\SessionService
    context: >
      apps\app\classier\context\WebContext
  swoole:
    session:
      key: PHPSESSID
      service: >
        apps\core\classier\service\SessionService
    context: >
      apps\app\classier\context\WebContext
    http:
      ip: 0.0.0.0
      port: 1800
      options:
        ssl_key_file: null
        ssl_cert_file: null
    websocket:
      ip: 0.0.0.0
      port: 1801
      return_key: __c
      options:
        ssl_key_file: null
        ssl_cert_file: null
        heartbeat_check_interval: 30
        heartbeat_idle_time: 30